// poly/index.ts
export * from "../poly-core"
export * from "../poly-2cat"
export * from "../poly-bouquet"
export * from "../operad-nerve"
export * from "../operad-core"
export * from "../poly-algebras"
export * from "../t-algebras-in-E"
export * from "../graphical"
export * from "../cartesian-morphism-poly"
export * from "../ts-category"
export * from "../exact-squares"
export * from "../kan-left-tstar"
export * from "../cocomplete-wrt"
export * from "../bar-resolution"
export * from "../nerve-segal"
